variables:
  SOLUTION_NAME: "DotnetCI"
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe'
  MSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\MSTest.exe'
  UNITTEST_FOLDER: '.\tests\CiCdExample.Tests\bin\'

before_script:
 - git remote -v
 - git remote rm origin

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  
  only:
    - branches

  script:
  - echo "Restoring NuGet Packages..."
  - '& "$env:NUGET_PATH" restore'
  
  - echo "Building..."
  - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  - '& "$env:MSBUILD_PATH" src\CiCdExample\CiCdExample.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=FolderProfile.pubxml'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\src\CiCdExample\bin\'
      - '$env:UNITTEST_FOLDER'
      - '.\$env:MSTEST_PATH\*.*'

test_job:
  stage: test
  
  script:
  - echo "Testing..."
  - '& "$env:MSTEST_PATH" /testcontainer:"$env:UNITTEST_FOLDER\CiCdExample.Tests.dll"'

deploy_job:
  stage: deploy
  only:
    - branches
  script:
    - 'xcopy /y /s ".\src\CiCdExample\bin\*.*" "C:\inetpub\wwwroot\ci-cd-example"'

  dependencies:
    - build_job

  