variables:
  SOLUTION_NAME: "DotnetCI"
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe'

before_script:

stages:
  - build
  - deploy

build_job:
  stage: build
  
  only:
    - branches

  script:
  - echo "Restoring NuGet Packages..."
  - '& "$env:NUGET_PATH" restore'
  
  - echo "Building"
  - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  - '& "$env:MSBUILD_PATH" src\CiCdExample\CiCdExample.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=FolderProfile.pubxml'
  artifacts:
  expire_in: 2 days
  paths:
      - '.\src\CiCdExample\bin\Release\Publish\'


deploy_job:
  stage: deploy
  only:
    - branches
  script:
    - 'xcopy /y /s ".\src\CiCdExample\bin\Release\Publish\*.*" "C:\inetpub\wwwroot\ci-cd-example"'

  dependencies:
    - build_job

  