variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe'


stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - branches
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
    - '& "$env:MSBUILD_PATH" src\CiCdExample\CiCdExample.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=FolderProfile.pubxml'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\src\CiCdExample.Web\bin\Release\Publish\'
      - '$env:UNITTEST_FOLDER'
      - '.\$env:XUNIT_PATH\*.*'

deploy_job:
  stage: deploy
  only:
    - branches
  script:
    - 'xcopy /y /s ".\src\CiCdExample.Web\bin\Release\Publish\*.*" "C:\Deployment\ci-cd-example"'

  dependencies:
    - build_job

  