variables:
  PROJECT_NAME: "DotnetCI"
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe'

before_script:
  - echo "starting build for %PROJECT_NAME%"
  - echo "Restoring NuGet Packages..."
  - 'C:\Tools\Nuget restore "%PROJECT_NAME%.sln"

stages:
  - build
  - deploy

build_job:
  stage: build
- echo "Starting build stage..."
  script:
     - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%.sln"'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\src\CiCdExample.Web\bin\Release\Publish\'

deploy_job:
  stage: deploy
  only:
    - branches
  script:
    - 'xcopy /y /s ".\src\CiCdExample.Web\bin\Release\Publish\*.*" "C:\Deployment\ci-cd-example"'

  dependencies:
    - build_job

  